### ISSUE TITLE
Registry returned 404

### ISSUE THREAD

**Issue by soetedja** [phfsantos/cordova-plugin-smaato#15]
Why i get an error 404 when installing the plugin?

Error: Registry returned 404 for GET on https://registry.npmjs.org/com.pherasoft.cordova-plugin-smaato

**Comment by phfsantos** [comment]
try https://registry.npmjs.org/cordova-plugin-smaato
com.pherasoft.cordova-plugin-smaato is to be used in cordova cli like cordova add com.pherasoft.cordova-plugin-smaato
