### ISSUE TITLE
does this plugin supports Windows Phone 10 with smaato new SDK

### ISSUE THREAD

**Issue by calebeaires** [phfsantos/cordova-plugin-smaato#8]
Smaato has update its sdk to support Windows 10. There is an windows on this platform. Admob dont have support to it yet, nether have some roadmap about it. Smaato seens to be the solution to cordova developers.

http://blog.smaato.com/publishers-monetize-windows-phone-10-new-sdk

**Comment by phfsantos** [comment]
No it does not support it. It does support windows phone 10 but not the SDK because it is not for js.
